### ISSUE TITLE
[CSS] 백 그라운드 이미지

### ISSUE THREAD

**Issue by parkhyosinfan** [codingeverybody/codingyahac#458]
# 해결하고자 하는 문제
블로그 상단에 글자 뒤에 배경으로 사진을 넣고 싶은데 넣어봐도 글 위로 올라가네요..
WEB수업에서 들었던 
https://source.unsplash.com/random 이곳을 활용해서 배경으로 넣고 위에
타이틀과 서브타이틀을 나타내고 싶은데 잘 되지 않네요 ㅠㅠ..

# 코드 혹은 오류
```
   여기에 코드를 적어주세요. 
<head>부분
<style>
#randomimg {
		background-image: url("https://source.unsplash.com/random");
</style>

<body>부분
<div id='header-wrapper' itemscope='itemscope' itemtype='http://schema.org/WPHeader'>
  <div id="randomimg">
  <b:section class='header section' id='header' maxwidgets='1' showaddelement='no'>
    <b:widget id='Header1' locked='true' title='F.I.T(헤더)' type='Header' version='1'>
(중략...)
</div>


원본 소스는
https://tmddn3020.blogspot.com 이곳에 있습니다!

**Comment by ghdalsrldi** [comment]
css 중괄호가 닫히지 않았네요

```css
<style>
#randomimg {
		background-image: url("https://source.unsplash.com/random");
</style>
```
위의 코드를 아래와 같이 바꿔 보세요
```css
<style>
#randomimg {
		background-image: url("https://source.unsplash.com/random");
}
</style>
```
