### ISSUE TITLE
pure javascript 로 touch scroll을 만들고 싶어요.

### ISSUE THREAD

**Issue by kammaii** [codingeverybody/codingyahac#589]
# 해결하고자 하는 문제

안녕하세요?
사실 좀 더 고민해보고 질문하려던 문제인데 벌써 코딩야학 종료일이 다가와서 급하게 질문 드립니다.

어떤 정해진 `<div>` 공간에 메시지를 보이게 하려고 합니다.
그런데 그 메시지가 길면 메시지가 정해진 공간에 다 표시가 되지 않아서
터치로 스크롤을 할 수 있게 하고 싶습니다.
검색을 해보니 주로 jquery같은 plug in을 이용한 예제들이 많이 나오는데 
저는 pure javascript로 기능을 만들고 싶습니다.
혹시 간단하게라도 참고할 수 있는 예제가 있을까요?

# 환경
javascript

**Comment by yoobato** [comment]
CSS의 [overflow-y](https://www.w3schools.com/cssref/css3_pr_overflow-y.asp) 속성을 사용하시면 됩니다.

```css
div {
  width: 200px;
  height: 100px;
  overflow-y: auto;
}
```

제가 예시를 만들어보았는데, 아래 링크 들어가셔서 코드를 확인해보시기 바랍니다.
https://codepen.io/yoobato/pen/ZVPPXg
