### ISSUE TITLE
박스모델 정렬방법

### ISSUE THREAD

**Issue by leekyujin** [codingeverybody/codingyahac#623]
# 해결하고자 하는 문제
박스모델을 한줄에 정렬하고 싶습니다.
구현하고자 하는 이미지는 하단과 같습니다.
https://xd.adobe.com/view/5e8fbfdb-4ab2-42af-7f62-dd626a48011e-28be/

# 코드 혹은 오류
**HTML**
<content>
		<div class="link01"><a href="whole.html">전국 주소록 리스트</a></div>
		<div class="link02"><a href="">서울,경기 주소록 리스트</a></div>
		<div class="link03"><a href="">지방권 주소록 리스트</a></div>
	</content>

**CSS**
content{
	display:inline-block;
	font-color:#6F5862;
	margin-top:77px;
}

.link01{
	width:216px;
	height:50px;
	background-color:#eaccb2;
	border-radius:30px;

}
.link02{
	width:216px;
	height:50px;
}
.link03{
	width:216px;
	height:50px;
	border-radius:30px
	background-color:#eaccb2;
}

# 환경
사용중인 운영체제, 언어, 라이브러리의 버전을 적어주세요.
windows10, html/css

# 시도해본 방법
inline block, float

**Comment by egoing** [comment]
원하시는 레이아웃이 무엇인지 정확하게 파악하기가 쉽지 않네요. ^^
대신 grid 라는 기법을 소개합니다. 
이 방법을 이용하면 거의 모든 레이아웃을 최소한의 코드 & 사고를 이용해서 만들 수 있답니다. 

아래 수업을 한번 참고해보세요. 
https://opentutorials.org/course/3086/18322

**Comment by yoobato** [comment]
.link01, .link02, .link03 각각에 `inline-block` 속성을 줘보시겠어요?

```css
.link01 {
  ...
  display: inline-block;
}

.link02 {
  ...
  display: inline-block;
}

.link03 {
  ...
  display: inline-block;
}
```
이런식으로요!
