### ISSUE TITLE
Html/css : 상단 메뉴바 구성 질문. 

### ISSUE THREAD

**Issue by jaejae-lee** [codingeverybody/codingyahac#731]
# 해결하고자 하는 문제
상단 헤더 메뉴바 구성.
1. 메뉴바 크기가 가로 사이즈로 화면에 꽉차게.
2. 화면 크기를 줄였을때 메뉴가 텍스트가 두 줄로 변환되지 않고, 전체적으로 폰트사이즈가 축소되도록. 

# 코드 혹은 오류
```
 <!DOCTYPE html>
<html lang="Ko">
<head>
    <meta charset="UTF-8">
    <title>React clone</title>
    <link rel="stylesheet" href="index.css"/>
</head>
<body>
<header class="navHeader">
    <nav>
        <span class="logo"><img src="" alt="logo"/></a></span>
        <ul class="menuLeft">
            <li class="menuItem"><a href="#">문서</a></li>
            <li class="menuItem"><a href="#">자습서</a></li>
            <li class="menuItem"><a href="#">블로그</a></li>
            <li class="menuItem"><a href="#">커뮤니티</a></li>   
        </ul>
            
        <ul class="menuRight">
            <li class="menuItem"><input type="text" placeholder="검색"/></li>
            <li class="menuItem"><a href="#">v16.8.6</a></li>
            <li class="menuItem"><a href="#">Languages</a></li>
            <li class="menuItem"><a href="#">Github</a></li>
        </ul>
    </nav>
</header>  

<div class="heroSpace">
    <div class="text1">React</div>
    <div class="text2">사용자 인터페이스를 만들기 위한 JavaScript 라이브러리</div>
    <div class="buttonWrap">
        <a class= "button1" href="#">시작하기</a>
        <a class= "button2" href="#">자습서 읽어보기 ></a>
    </div>
</div>

<section>
    <h1>선언형</h1>
    <P>
        React는 상호작용이 많은 UI를 만들 때 생기는 어려움을 줄여줍니다. 애플리케이션의 각 상태에 대한 간단한 뷰만 설계하세요. 그럼 React는 데이터가 변경됨에 따라 적절한 컴포넌트만 효율적으로 갱신하고 렌더링합니다.
        선언형 뷰는 코드를 예측 가능하고 디버그하기 쉽게 만들어 줍니다.
    </P>
</section>
<section>
    <h1>선언형</h1>
    <P>
        React는 상호작용이 많은 UI를 만들 때 생기는 어려움을 줄여줍니다. 애플리케이션의 각 상태에 대한 간단한 뷰만 설계하세요. 그럼 React는 데이터가 변경됨에 따라 적절한 컴포넌트만 효율적으로 갱신하고 렌더링합니다.
        선언형 뷰는 코드를 예측 가능하고 디버그하기 쉽게 만들어 줍니다.
    </P>
</section>
<section>
    <h1>선언형</h1>
    <P>
        React는 상호작용이 많은 UI를 만들 때 생기는 어려움을 줄여줍니다. 애플리케이션의 각 상태에 대한 간단한 뷰만 설계하세요. 그럼 React는 데이터가 변경됨에 따라 적절한 컴포넌트만 효율적으로 갱신하고 렌더링합니다.
        선언형 뷰는 코드를 예측 가능하고 디버그하기 쉽게 만들어 줍니다.
    </P>
</section>
<div class="liveEditor">LiveEditer</div>
<div class="buttonWrap">
        <a class= "button1" href="#">시작하기</a>
        <a class= "button2" href="#">자습서 읽어보기 ></a>
</div>
</body>
<footer>
    footer
    footer
    footer
    footer
    footer
</footer>

</html>
```

```
body {
    margin: 0;
    padding: 0;
}

header {
    background : rgb(30, 30, 37);
    position: fixed;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
}

header nav {
    display: flex;
    align-items: center; 
}

header nav ul {
    list-style: none;
}

header nav ul li{
    float: left;
    margin: 20px;
    font-size: 20px;
}

.logo {
    padding: 0 100px;
}

.menuLeft {
    margin: 0;
    padding: 0 100px;
}

.menuRight {
    margin: 0;
    padding: 0 200px 0 200px ;
}

a {
    color: white;
    text-decoration: none;
}


.heroSpace {
    background: rgb(42, 45, 54);
    padding: 200px 0 50px 0;
    text-align: center;
}

.text1 {
    font-size: 4.5rem;
    color: rgb(0, 183, 255);
}

.text2 {
    font-size: 2rem;
    color: white;
    margin:
}

.buttonWrap {
    display: flex;
    flex-direction: row;
    margin: auto;
    justify-content: center;
    margin: 80px 0;
}

.button1 {
    background: rgb(0, 183, 255);
    color: black;
    width: 8rem;
    text-align: center;
    display: block;
    font-size: 20px;
    padding: 10px;
    margin: 0 30px 0 0;
}

.button2 {
    background:none;
    color: rgb(0, 183, 255);
    width: 9rem;
    text-align: center;
    display: block;
    font-size: 20px;
    padding: 10px;
}

.button1:hover {
    background: white;
    color:black;
}

.button2:hover {
    color: white;
}

footer{
    background : rgb(30, 30, 37);
    color: white;
}

```

# 환경
Mac OS.
HTML5/CSS

# 시도해본 방법
헤더바를 패딩과마진 픽셀조정으로 해보려니 잘 안됩니다ㅠ 
혹시 제가 메뉴바를 구성한 코드 자체가 맞는 방법인지 잘 모르겠습니다.
전체 코드로 첨부드려요!

**Comment by Hatser** [comment]
```css
body {
    margin: 0;
    padding: 0;
}

header {
    background : rgb(30, 30, 37);
    position: fixed;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    width: 100%;
}

header nav {
    display: block;
    align-items: center;
    height: fit-content;
    width: 100%;
}

header nav ul {
    list-style: none;
    display: block;
}

header nav ul li{
    display: inline-block;
    margin: 20px;
    font-size: 2vw;
}

.logo {
    display: block;
    text-align: center;
}

.menuLeft, .menuRight {
    margin: 0;
    text-align: center;
}

a {
    color: white;
    text-decoration: none;
}


.heroSpace {
    background: rgb(42, 45, 54);
    padding: 200px 0 50px 0;
    text-align: center;
}

.text1 {
    font-size: 4.5rem;
    color: rgb(0, 183, 255);
}

.text2 {
    font-size: 2rem;
    color: white;
    margin:
}

.buttonWrap {
    display: flex;
    flex-direction: row;
    margin: auto;
    justify-content: center;
    margin: 80px 0;
}

.button1 {
    background: rgb(0, 183, 255);
    color: black;
    width: 8rem;
    text-align: center;
    display: block;
    font-size: 20px;
    padding: 10px;
    margin: 0 30px 0 0;
}

.button2 {
    background:none;
    color: rgb(0, 183, 255);
    width: 9rem;
    text-align: center;
    display: block;
    font-size: 20px;
    padding: 10px;
}

.button1:hover {
    background: white;
    color:black;
}

.button2:hover {
    color: white;
}

footer{
    background : rgb(30, 30, 37);
    color: white;
}
```

[적용 결과](https://jsfiddle.net/br3a0d2k/)

바뀐 내용은 [여기](https://www.diffchecker.com/21enTjbg)서 찾아볼 수 있습니다.
(링크 한 달 간 유효)

바뀐 내용들을 한 두개씩 바꿔가면서 적용해보시고, 어떻게 달라지는지 확인하시면

이후에 화면 구성하는 감각이 조금씩 생길 거에요!
