### ISSUE TITLE
프로젝트 구축의 고민, 백그라운드이미지만 투명하게 리뷰 (참조 :https://github.com/codingeverybody/codingyahac/issues/657)

### ISSUE THREAD

**Issue by Eunseung** [codingeverybody/codingyahac#741]
#해결하고자 하는 문제
생활코딩의WEBn시리즈를 통해서
HTML,CSS,JS 를 독학을 했습니다. 
그리고
웹사이트 작성에 있어서 그림으로 기획을하고 코딩을 하던중 그림에만 초점이 맞춰지다보니, 
HTML을 끝내고 내 프로젝트를 작성하면 여러가지 불편함들을 CSS에서 처리할 수 있었겠지만,
지금은 JS까지 본상태라서 지식의 혼란이 온 시기입니다. 

데이터는 없는데 CSS를 맞추려고 보니 프로젝트의 본질을 잃어가고 있는듯한 느낌이 드네요.

지금까지의 상황은
1. 이미지상으로만 사이트 구축의 그림이 그려집니다.
2. 네이버블로그, 인스타그램 을 통해서 데이터를 추출해오고싶은데, WEB2(PHP, Python, Node.js) 를 통해서 배워야한다는 것은 질문을 통해서 배우게 되었습니다. 그런데 또 지식의 홍수에 같히게될까봐 걱정입니다.

-> 정확한데이터를 구축하고, HTML, JS, WEB2를 통해 코딩을 하고 마지막으로 CSS를 입힐까요?

# 코드 혹은 오류
배경 이미지만 투명도를 주고싶었는데, 잘 되지않았습니다.

# 환경
Windows10, HTML, CSS, JS

# 시도해본 방법
opacity 를 CSS페이지의 Body에 입혔습니다.
기획의 의도대로 하기 위하여 
생활코딩 페이지의 
'사진 중심의 웹사이트'와 '썸네일만들기'를 참조하였습니다.
밑의 사진은 구축한 페이지와 코드입니다.
![코드](https://user-images.githubusercontent.com/49604556/62513302-88015e00-b856-11e9-88f2-63755ce572f1.jpg)
![사이트](https://user-images.githubusercontent.com/49604556/62513303-8899f480-b856-11e9-85df-ad55ac2f07b9.jpg)

**Comment by Hatser** [comment]
body에 투명도를 주게되면, 내부 요소들도 모두 투명해지게 됩니다.

배경을 담아두기 위한 요소를 하나 만드시고, 
```html
<body>
    <div class="bg-image"></div>
</body>
```

이 요소가 다른요소들과 충돌하지 않도록 설정한 후, 다른 요소들보다 뒤쪽에 위치하도록 하시면 됩니다.

```css
body {
  padding: 0;
  margin: 0;
}

.bg-image {
  position:absolute;
  width:100vw; /* 또는 100% */
  height:100vh; /* 또는 100% */
  background-image: url(background.jpg);
  background-size: cover;
  opacity: 0.5;
  z-index: -1;
}
```
