### ISSUE TITLE
h1과 li 컬러변경이 안되네요 ㅠㅠ

### ISSUE THREAD

**Issue by ThisIsJoHan** [codingeverybody/codingyahac#813]
![image](https://user-images.githubusercontent.com/53946668/63027403-dc0be280-bee7-11e9-9fb3-3b8715046205.png)

왜 h1이 green으로 안바뀌고
li도 black으로 안바뀔까요...

아래는 인덱스 코드입니다.
![image](https://user-images.githubusercontent.com/53946668/63027473-ffcf2880-bee7-11e9-8cfb-9a1c748a5d2a.png)

**Comment by yoobato** [comment]
`h1` 과 `li` 태그 안에 `a` 태그가 존재해서 그렇습니다.

1) 우선, CSS가 적용되는 순서는, 가장 바깥 쪽 태그부터 적용되어서, 마지막에 가장 안 쪽의 태그가 적용됩니다. 즉, 예를 들어, 바깥 쪽 `h1`이 `color: green`으로 설정되어 있어도, `a`가 `color: red`로 설정되어 있으면, 빨간색으로 나오게 됩니다. `a` 태그를 `h1` 과 `li`태그 밖으로 빼서, `a` 태그가 `h1` 과 `li`을 감싸게 만들면 되실겁니다.

2) 만약, `a` 태그를 계속 안 쪽에 두고 싶으시다면, `h1` 과 `li` 태그의 CSS 스타일 적용 부분에서, `color` 부분에 `!important`를 추가하시는 것도 방법입니다.
 ```css
h1 {
  color: green !important;
  ...나머지
}

li {
  color: black !important;
  ...나머지
}
```
`!important`를 사용하시면, CSS 스타일이 적용되는 우선순위를 강제로 가장 높게 설정합니다. 이와 관련해서는, 아래 [여기](https://aboooks.tistory.com/120)를 참고해보시면 좋을 것 같습니다.

3) a 태그의 경우 대부분의 웹브라우저에서 기본적으로 한 번 이상 클릭해서 방문한 적(visited)이 있는 경우, 올려주신 스크린샷과 같이 보라색으로 띄우게 됩니다. 즉, 아무리 바깥의 태그에서 색상을 설정해도, 보라색으로 설정되는 것이 우선순위가 더 높게 되는데요. 이를, CSS의 Pseudo-class 를 이용해서, 무시해줄 수 있습니다. CSS Pseudo-class와 관련해서는 [여기](https://www.w3schools.com/css/css_pseudo_classes.asp)를 참고해보세요!

CSS 설정 부분에 아래 코드를 추가하시면, 바깥 쪽 태그의 속성을 그대로 이용하게 됩니다.
```css
a, a:visited, a:hover, a:active {
  color: inherit;
}
```
